---

- name: drop SSH key
  authorized_key:
    user: "{{ user_name }}"
    state: absent
    key: "{{ lookup('file', '../../../sshkeys/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - revoke

- name: userdel
  user:
    name: "{{ user_name }}"
    state: absent
    remove: yes
  tags:
    - remove
